### ISSUE TITLE
Image cropping

### ISSUE THREAD

**Issue by RebeccaJWilson** [machine-shop/butterfly-wings#33]
Hi @stefanv  
Phil Fenberg and I have been running some tests on specimens we have already measured, but we noticed when we used the updated pipeline.py code with the updated binarization module (binarize tags finding fix) that on some specimens it is now cropping the image in the wrong place meaning that part of the right hand wing is cut off.  I've attached a couple of examples for you (with the plots given by the older code and the new updated code) for the silver-spotted skipper. It also had the same issue when we tested it on another species. 

![bmnhe_1353199_new code](https://user-images.githubusercontent.com/48092348/53576785-5d56ff00-3b6c-11e9-8af3-c8c29dec1bdd.JPG)
![bmnhe_1353199_original](https://user-images.githubusercontent.com/48092348/53576792-61831c80-3b6c-11e9-854e-1bf7e7191327.JPG)
![bmnhe_1353957_new code](https://user-images.githubusercontent.com/48092348/53576834-76f84680-3b6c-11e9-8564-c7a0e7e9da5c.JPG)
![bmnhe_1353957_original](https://user-images.githubusercontent.com/48092348/53576842-7bbcfa80-3b6c-11e9-941d-f26112aef6cc.JPG)

**Comment by denniscfeng** [comment]
Hi Rebecca,

This issue should be fixed in the newest push of the code. Please let me know if there continue to be such problems. We are aware that there are certain images that suffer cropping problems, and we're currently working on a fix to take care of them. Sorry for the delay, and please provide any feedback if there are other issues.

**Comment by RebeccaJWilson** [comment]
Yes, have re-run the images using the new code and it has fixed the issue. Thank you.
